### PR TITLE
Switch from Travis to Github Actions

### PR DESCRIPTION
**Pull request by addshore**

### CODE REVIEW

**Comment by addshore** [comment]
Failing because of `ERROR: Referenced sniff "MediaWiki.PHP70Features" does not exist` O_o

**Comment by JeroenDeDauw** [comment]
I've started just removing that CS in many of my repos. Takes more time to deal with it than it saves

**Comment by JeroenDeDauw** [comment]
I think it generally better to separate tests and static analysis. Like done here https://github.com/ProfessionalWiki/EDTF/blob/master/.github/workflows/ci.yml

(General remark. Don't think it worth spending much time on this repo)

**Comment by JeroenDeDauw** [comment]
https://github.com/DataValues/Interfaces/pull/55

**Review by JeroenDeDauw — APPROVED** [review]

**Comment by JeroenDeDauw** [comment]
@addshore

**Pull request merged**
